#!/bin/bash 
#SBATCH --job-name=mpi_job ### name your job 
#SBATCH --time=00:10:00		 ### hh:mm:ss or dd-hh:mm:ss
#SBATCH --mem=16G				 ### memory setting is max @ 125 MB per core
#SBATCH --ntasks=128			 ### launch 128 mpi processes
#SBATCH --cpus-per-task=1		 ### single-threaded processes
#SBATCH --ntasks-per-node=16   ### 16 mpi processes per node
#SBATCH --output=mpi.%j.out
#SBATCH --partition=defq


module load openmpi/4.1.5-gcc-11.2.0-ux65npg

if [ ! -f mpi ]
then
 mpicc mpi.c -o mpi
else
 if [ mpi.c -nt mpi ]
 then
  mpicc mpi.c -o mpi
 fi
fi

srun mpi

exit 0
